# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server_v2.apis.assistants_api import router as AssistantsApiRouter
from openapi_server_v2.apis.audio_api import router as AudioApiRouter
from openapi_server_v2.apis.batch_api import router as BatchApiRouter
from openapi_server_v2.apis.chat_api import router as ChatApiRouter
from openapi_server_v2.apis.completions_api import router as CompletionsApiRouter
from openapi_server_v2.apis.embeddings_api import router as EmbeddingsApiRouter
from openapi_server_v2.apis.files_api import router as FilesApiRouter
from openapi_server_v2.apis.fine_tuning_api import router as FineTuningApiRouter
from openapi_server_v2.apis.images_api import router as ImagesApiRouter
from openapi_server_v2.apis.models_api import router as ModelsApiRouter
from openapi_server_v2.apis.moderations_api import router as ModerationsApiRouter
from openapi_server_v2.apis.vector_stores_api import router as VectorStoresApiRouter

app = FastAPI(
    title="OpenAI API",
    description="The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.",
    version="2.0.0",
)

app.include_router(AssistantsApiRouter)
app.include_router(AudioApiRouter)
app.include_router(BatchApiRouter)
app.include_router(ChatApiRouter)
app.include_router(CompletionsApiRouter)
app.include_router(EmbeddingsApiRouter)
app.include_router(FilesApiRouter)
app.include_router(FineTuningApiRouter)
app.include_router(ImagesApiRouter)
app.include_router(ModelsApiRouter)
app.include_router(ModerationsApiRouter)
app.include_router(VectorStoresApiRouter)
