name: Run tests

on: 
  workflow_dispatch:

jobs:

  run-astra-assistants-tests-chat:
    runs-on: ubuntu-latest
    name: run astra-assistants cat tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_chat_completion.py

  run-astra-assistants-tests-embedding:
    runs-on: ubuntu-latest
    name: run astra-assistants embedding tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_embedding.py
  run-astra-assistants-tests-file-embedding:
    runs-on: ubuntu-latest
    name: run astra-assistants file embedding tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_file_embedding.py
  run-astra-assistants-tests-function-calling:
    runs-on: ubuntu-latest
    name: run astra-assistants function calling tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_function_calling.py
  run-astra-assistants-tests-run:
    runs-on: ubuntu-latest
    name: run astra-assistants run tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_run.py
  run-astra-assistants-tests-run-retrieval:
    runs-on: ubuntu-latest
    name: run astra-assistants run retrieval tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_run_retreival.py
  run-astra-assistants-tests-create-and-stream-run:
    runs-on: ubuntu-latest
    name: run astra-assistants create and stream run tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_create_and_stream_run.py
  run-astra-assistants-tests-streaming-function-calling:
    runs-on: ubuntu-latest
    name: run astra-assistants streaming function calling tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_streaming_function_calling.py
  run-astra-assistants-tests-streaming-calling-run:
    runs-on: ubuntu-latest
    name: run astra-assistants streaming run tests
    env:
        ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        base_url: ${{ secrets.BASE_URL }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITYAI_API_KEY: ${{ secrets.PERPLEXITYAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: '3.10.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Check Poetry Version
        run: poetry --version
      - name: Configure Poetry to Use Python 3.10.12
        run: poetry env use python3.10
      - name: get dependencies
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest -s --disable-warnings tests/test_streaming_run.py
