# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AssistantFileObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AssistantFileObject - a model defined in OpenAPI

        id: The id of this AssistantFileObject.
        object: The object of this AssistantFileObject.
        created_at: The created_at of this AssistantFileObject.
        assistant_id: The assistant_id of this AssistantFileObject.
    """

    id: str = Field(alias="id")
    object: str = Field(alias="object")
    created_at: int = Field(alias="created_at")
    assistant_id: str = Field(alias="assistant_id")

AssistantFileObject.update_forward_refs()
