# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_message_tool_call import ChatCompletionMessageToolCall
from openapi_server.models.chat_completion_request_assistant_message_function_call import ChatCompletionRequestAssistantMessageFunctionCall


class ChatCompletionRequestAssistantMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionRequestAssistantMessage - a model defined in OpenAPI

        content: The content of this ChatCompletionRequestAssistantMessage [Optional].
        role: The role of this ChatCompletionRequestAssistantMessage.
        name: The name of this ChatCompletionRequestAssistantMessage [Optional].
        tool_calls: The tool_calls of this ChatCompletionRequestAssistantMessage [Optional].
        function_call: The function_call of this ChatCompletionRequestAssistantMessage [Optional].
    """

    content: Optional[str] = Field(alias="content", default=None)
    role: str = Field(alias="role")
    name: Optional[str] = Field(alias="name", default=None)
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = Field(alias="tool_calls", default=None)
    function_call: Optional[ChatCompletionRequestAssistantMessageFunctionCall] = Field(alias="function_call", default=None)

ChatCompletionRequestAssistantMessage.update_forward_refs()
