# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_request_message_content_part_image_image_url import ChatCompletionRequestMessageContentPartImageImageUrl


class ChatCompletionRequestMessageContentPartImage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionRequestMessageContentPartImage - a model defined in OpenAPI

        type: The type of this ChatCompletionRequestMessageContentPartImage.
        image_url: The image_url of this ChatCompletionRequestMessageContentPartImage.
    """

    type: str = Field(alias="type")
    image_url: ChatCompletionRequestMessageContentPartImageImageUrl = Field(alias="image_url")

ChatCompletionRequestMessageContentPartImage.update_forward_refs()
