# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_named_tool_choice_function import ChatCompletionNamedToolChoiceFunction


class ChatCompletionNamedToolChoice(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionNamedToolChoice - a model defined in OpenAPI

        type: The type of this ChatCompletionNamedToolChoice.
        function: The function of this ChatCompletionNamedToolChoice.
    """

    type: str = Field(alias="type")
    function: ChatCompletionNamedToolChoiceFunction = Field(alias="function")

ChatCompletionNamedToolChoice.update_forward_refs()
