# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ChatCompletionRequestAssistantMessageFunctionCall(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionRequestAssistantMessageFunctionCall - a model defined in OpenAPI

        arguments: The arguments of this ChatCompletionRequestAssistantMessageFunctionCall.
        name: The name of this ChatCompletionRequestAssistantMessageFunctionCall.
    """

    arguments: str = Field(alias="arguments")
    name: str = Field(alias="name")

ChatCompletionRequestAssistantMessageFunctionCall.update_forward_refs()
