# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ChatCompletionStreamResponseDeltaFunctionCall(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionStreamResponseDeltaFunctionCall - a model defined in OpenAPI

        arguments: The arguments of this ChatCompletionStreamResponseDeltaFunctionCall [Optional].
        name: The name of this ChatCompletionStreamResponseDeltaFunctionCall [Optional].
    """

    arguments: Optional[str] = Field(alias="arguments", default=None)
    name: Optional[str] = Field(alias="name", default=None)

ChatCompletionStreamResponseDeltaFunctionCall.update_forward_refs()
