# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ChatCompletionRequestMessageContentPartImageImageUrl(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionRequestMessageContentPartImageImageUrl - a model defined in OpenAPI

        url: The url of this ChatCompletionRequestMessageContentPartImageImageUrl.
        detail: The detail of this ChatCompletionRequestMessageContentPartImageImageUrl [Optional].
    """

    url: AnyUrl = Field(alias="url")
    detail: Optional[str] = Field(alias="detail", default=None)

ChatCompletionRequestMessageContentPartImageImageUrl.update_forward_refs()
