# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ChatCompletionRequestSystemMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionRequestSystemMessage - a model defined in OpenAPI

        content: The content of this ChatCompletionRequestSystemMessage.
        role: The role of this ChatCompletionRequestSystemMessage.
        name: The name of this ChatCompletionRequestSystemMessage [Optional].
    """

    content: str = Field(alias="content")
    role: str = Field(alias="role")
    name: Optional[str] = Field(alias="name", default=None)

ChatCompletionRequestSystemMessage.update_forward_refs()
