# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_message_tool_call import ChatCompletionMessageToolCall
from openapi_server.models.chat_completion_request_assistant_message_function_call import ChatCompletionRequestAssistantMessageFunctionCall


class ChatCompletionResponseMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionResponseMessage - a model defined in OpenAPI

        content: The content of this ChatCompletionResponseMessage.
        tool_calls: The tool_calls of this ChatCompletionResponseMessage [Optional].
        role: The role of this ChatCompletionResponseMessage.
        function_call: The function_call of this ChatCompletionResponseMessage [Optional].
    """

    content: str = Field(alias="content")
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = Field(alias="tool_calls", default=None)
    role: str = Field(alias="role")
    function_call: Optional[ChatCompletionRequestAssistantMessageFunctionCall] = Field(alias="function_call", default=None)

ChatCompletionResponseMessage.update_forward_refs()
