# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_message_tool_call_chunk_function import ChatCompletionMessageToolCallChunkFunction


class ChatCompletionMessageToolCallChunk(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionMessageToolCallChunk - a model defined in OpenAPI

        index: The index of this ChatCompletionMessageToolCallChunk.
        id: The id of this ChatCompletionMessageToolCallChunk [Optional].
        type: The type of this ChatCompletionMessageToolCallChunk [Optional].
        function: The function of this ChatCompletionMessageToolCallChunk [Optional].
    """

    index: int = Field(alias="index")
    id: Optional[str] = Field(alias="id", default=None)
    type: Optional[str] = Field(alias="type", default=None)
    function: Optional[ChatCompletionMessageToolCallChunkFunction] = Field(alias="function", default=None)

ChatCompletionMessageToolCallChunk.update_forward_refs()
