# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ChatCompletionRequestFunctionMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionRequestFunctionMessage - a model defined in OpenAPI

        role: The role of this ChatCompletionRequestFunctionMessage.
        content: The content of this ChatCompletionRequestFunctionMessage.
        name: The name of this ChatCompletionRequestFunctionMessage.
    """

    role: str = Field(alias="role")
    content: str = Field(alias="content")
    name: str = Field(alias="name")

ChatCompletionRequestFunctionMessage.update_forward_refs()
