# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ChatCompletionRequestToolMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionRequestToolMessage - a model defined in OpenAPI

        role: The role of this ChatCompletionRequestToolMessage.
        content: The content of this ChatCompletionRequestToolMessage.
        tool_call_id: The tool_call_id of this ChatCompletionRequestToolMessage.
    """

    role: str = Field(alias="role")
    content: str = Field(alias="content")
    tool_call_id: str = Field(alias="tool_call_id")

ChatCompletionRequestToolMessage.update_forward_refs()
