# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ChatCompletionTokenLogprob(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChatCompletionTokenLogprob - a model defined in OpenAPI

        token: The token of this ChatCompletionTokenLogprob.
        logprob: The logprob of this ChatCompletionTokenLogprob.
        bytes: The bytes of this ChatCompletionTokenLogprob.
        top_logprobs: The top_logprobs of this ChatCompletionTokenLogprob.
    """

    token: str = Field(alias="token")
    logprob: float = Field(alias="logprob")
    bytes: List[int] = Field(alias="bytes")
    top_logprobs: List[object] = Field(alias="top_logprobs")

ChatCompletionTokenLogprob.update_forward_refs()
