# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CreateEditResponseChoicesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateEditResponseChoicesInner - a model defined in OpenAPI

        finish_reason: The finish_reason of this CreateEditResponseChoicesInner.
        index: The index of this CreateEditResponseChoicesInner.
        text: The text of this CreateEditResponseChoicesInner.
    """

    finish_reason: str = Field(alias="finish_reason")
    index: int = Field(alias="index")
    text: str = Field(alias="text")

CreateEditResponseChoicesInner.update_forward_refs()
