# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_fine_tuning_job_request_hyperparameters_batch_size import CreateFineTuningJobRequestHyperparametersBatchSize
from openapi_server.models.create_fine_tuning_job_request_hyperparameters_learning_rate_multiplier import CreateFineTuningJobRequestHyperparametersLearningRateMultiplier
from openapi_server.models.create_fine_tuning_job_request_hyperparameters_n_epochs import CreateFineTuningJobRequestHyperparametersNEpochs


class CreateFineTuningJobRequestHyperparameters(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateFineTuningJobRequestHyperparameters - a model defined in OpenAPI

        batch_size: The batch_size of this CreateFineTuningJobRequestHyperparameters [Optional].
        learning_rate_multiplier: The learning_rate_multiplier of this CreateFineTuningJobRequestHyperparameters [Optional].
        n_epochs: The n_epochs of this CreateFineTuningJobRequestHyperparameters [Optional].
    """

    batch_size: Optional[CreateFineTuningJobRequestHyperparametersBatchSize] = Field(alias="batch_size", default=None)
    learning_rate_multiplier: Optional[CreateFineTuningJobRequestHyperparametersLearningRateMultiplier] = Field(alias="learning_rate_multiplier", default=None)
    n_epochs: Optional[CreateFineTuningJobRequestHyperparametersNEpochs] = Field(alias="n_epochs", default=None)

CreateFineTuningJobRequestHyperparameters.update_forward_refs()
