# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_moderation_request_input import CreateModerationRequestInput
from openapi_server.models.create_moderation_request_model import CreateModerationRequestModel


class CreateModerationRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateModerationRequest - a model defined in OpenAPI

        input: The input of this CreateModerationRequest.
        model: The model of this CreateModerationRequest [Optional].
    """

    input: CreateModerationRequestInput = Field(alias="input")
    model: Optional[CreateModerationRequestModel] = Field(alias="model", default=None)

CreateModerationRequest.update_forward_refs()
