# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CreateTranslationResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateTranslationResponse - a model defined in OpenAPI

        text: The text of this CreateTranslationResponse.
    """

    text: str = Field(alias="text")

CreateTranslationResponse.update_forward_refs()
