# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_function_call_option import ChatCompletionFunctionCallOption


class CreateChatCompletionRequestFunctionCall(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateChatCompletionRequestFunctionCall - a model defined in OpenAPI

        name: The name of this CreateChatCompletionRequestFunctionCall.
    """

    name: str = Field(alias="name")

CreateChatCompletionRequestFunctionCall.update_forward_refs()
