# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_thread_and_run_request_tools_inner import CreateThreadAndRunRequestToolsInner
from openapi_server.models.create_thread_request import CreateThreadRequest


class CreateThreadAndRunRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateThreadAndRunRequest - a model defined in OpenAPI

        assistant_id: The assistant_id of this CreateThreadAndRunRequest.
        thread: The thread of this CreateThreadAndRunRequest [Optional].
        model: The model of this CreateThreadAndRunRequest [Optional].
        instructions: The instructions of this CreateThreadAndRunRequest [Optional].
        tools: The tools of this CreateThreadAndRunRequest [Optional].
        metadata: The metadata of this CreateThreadAndRunRequest [Optional].
    """

    assistant_id: str = Field(alias="assistant_id")
    thread: Optional[CreateThreadRequest] = Field(alias="thread", default=None)
    model: Optional[str] = Field(alias="model", default=None)
    instructions: Optional[str] = Field(alias="instructions", default=None)
    tools: Optional[List[CreateThreadAndRunRequestToolsInner]] = Field(alias="tools", default=None)
    metadata: Optional[Dict[str, Any]] = Field(alias="metadata", default=None)

CreateThreadAndRunRequest.update_forward_refs()
