# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_completion_response_choices_inner_logprobs import CreateCompletionResponseChoicesInnerLogprobs


class CreateCompletionResponseChoicesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateCompletionResponseChoicesInner - a model defined in OpenAPI

        finish_reason: The finish_reason of this CreateCompletionResponseChoicesInner.
        index: The index of this CreateCompletionResponseChoicesInner.
        logprobs: The logprobs of this CreateCompletionResponseChoicesInner.
        text: The text of this CreateCompletionResponseChoicesInner.
    """

    finish_reason: str = Field(alias="finish_reason")
    index: int = Field(alias="index")
    logprobs: CreateCompletionResponseChoicesInnerLogprobs = Field(alias="logprobs")
    text: str = Field(alias="text")

CreateCompletionResponseChoicesInner.update_forward_refs()
