# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_embedding_response_usage import CreateEmbeddingResponseUsage
from openapi_server.models.embedding import Embedding


class CreateEmbeddingResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateEmbeddingResponse - a model defined in OpenAPI

        data: The data of this CreateEmbeddingResponse.
        model: The model of this CreateEmbeddingResponse.
        object: The object of this CreateEmbeddingResponse.
        usage: The usage of this CreateEmbeddingResponse.
    """

    data: List[Embedding] = Field(alias="data")
    model: str = Field(alias="model")
    object: str = Field(alias="object")
    usage: CreateEmbeddingResponseUsage = Field(alias="usage")

CreateEmbeddingResponse.update_forward_refs()
