# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_response_message import ChatCompletionResponseMessage
from openapi_server.models.create_chat_completion_response_choices_inner_logprobs import CreateChatCompletionResponseChoicesInnerLogprobs


class CreateChatCompletionResponseChoicesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateChatCompletionResponseChoicesInner - a model defined in OpenAPI

        finish_reason: The finish_reason of this CreateChatCompletionResponseChoicesInner.
        index: The index of this CreateChatCompletionResponseChoicesInner.
        message: The message of this CreateChatCompletionResponseChoicesInner.
        logprobs: The logprobs of this CreateChatCompletionResponseChoicesInner.
    """

    finish_reason: str = Field(alias="finish_reason")
    index: int = Field(alias="index")
    message: ChatCompletionResponseMessage = Field(alias="message")
    logprobs: Optional[CreateChatCompletionResponseChoicesInnerLogprobs] = Field(alias="logprobs")

CreateChatCompletionResponseChoicesInner.update_forward_refs()
