# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.completion_usage import CompletionUsage
from openapi_server.models.create_chat_completion_function_response_choices_inner import CreateChatCompletionFunctionResponseChoicesInner


class CreateChatCompletionFunctionResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateChatCompletionFunctionResponse - a model defined in OpenAPI

        id: The id of this CreateChatCompletionFunctionResponse.
        choices: The choices of this CreateChatCompletionFunctionResponse.
        created: The created of this CreateChatCompletionFunctionResponse.
        model: The model of this CreateChatCompletionFunctionResponse.
        system_fingerprint: The system_fingerprint of this CreateChatCompletionFunctionResponse [Optional].
        object: The object of this CreateChatCompletionFunctionResponse.
        usage: The usage of this CreateChatCompletionFunctionResponse [Optional].
    """

    id: str = Field(alias="id")
    choices: List[CreateChatCompletionFunctionResponseChoicesInner] = Field(alias="choices")
    created: int = Field(alias="created")
    model: str = Field(alias="model")
    system_fingerprint: Optional[str] = Field(alias="system_fingerprint", default=None)
    object: str = Field(alias="object")
    usage: Optional[CompletionUsage] = Field(alias="usage", default=None)

CreateChatCompletionFunctionResponse.update_forward_refs()
