# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CreateCompletionResponseChoicesInnerLogprobs(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateCompletionResponseChoicesInnerLogprobs - a model defined in OpenAPI

        text_offset: The text_offset of this CreateCompletionResponseChoicesInnerLogprobs [Optional].
        token_logprobs: The token_logprobs of this CreateCompletionResponseChoicesInnerLogprobs [Optional].
        tokens: The tokens of this CreateCompletionResponseChoicesInnerLogprobs [Optional].
        top_logprobs: The top_logprobs of this CreateCompletionResponseChoicesInnerLogprobs [Optional].
    """

    text_offset: Optional[List[int]] = Field(alias="text_offset", default=None)
    token_logprobs: Optional[List[float]] = Field(alias="token_logprobs", default=None)
    tokens: Optional[List[str]] = Field(alias="tokens", default=None)
    top_logprobs: Optional[List[Dict[str, float]]] = Field(alias="top_logprobs", default=None)

CreateCompletionResponseChoicesInnerLogprobs.update_forward_refs()
