# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_edit_response_choices_inner import CreateEditResponseChoicesInner


class CreateEditResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateEditResponse - a model defined in OpenAPI

        choices: The choices of this CreateEditResponse [Optional].
    """

    choices: Optional[List[CreateEditResponseChoicesInner]] = Field(alias="choices", default=None)

CreateEditResponse.update_forward_refs()
