# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_response_message import ChatCompletionResponseMessage


class CreateChatCompletionFunctionResponseChoicesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateChatCompletionFunctionResponseChoicesInner - a model defined in OpenAPI

        finish_reason: The finish_reason of this CreateChatCompletionFunctionResponseChoicesInner.
        index: The index of this CreateChatCompletionFunctionResponseChoicesInner.
        message: The message of this CreateChatCompletionFunctionResponseChoicesInner.
    """

    finish_reason: str = Field(alias="finish_reason")
    index: int = Field(alias="index")
    message: ChatCompletionResponseMessage = Field(alias="message")

CreateChatCompletionFunctionResponseChoicesInner.update_forward_refs()
