# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_image_request_model import CreateImageRequestModel


class CreateImageRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateImageRequest - a model defined in OpenAPI

        prompt: The prompt of this CreateImageRequest.
        model: The model of this CreateImageRequest [Optional].
        n: The n of this CreateImageRequest [Optional].
        quality: The quality of this CreateImageRequest [Optional].
        response_format: The response_format of this CreateImageRequest [Optional].
        size: The size of this CreateImageRequest [Optional].
        style: The style of this CreateImageRequest [Optional].
    """

    prompt: str = Field(alias="prompt")
    model: Optional[CreateImageRequestModel] = Field(alias="model", default=None)
    n: Optional[int] = Field(alias="n", default=None)
    quality: Optional[str] = Field(alias="quality", default=None)
    response_format: Optional[str] = Field(alias="response_format", default=None)
    size: Optional[str] = Field(alias="size", default=None)
    style: Optional[str] = Field(alias="style", default=None)

    @validator("n")
    def n_max(cls, value):
        assert value <= 10
        return value

    @validator("n")
    def n_min(cls, value):
        assert value >= 1
        return value

CreateImageRequest.update_forward_refs()
