# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.chat_completion_stream_response_delta import ChatCompletionStreamResponseDelta


class CreateChatCompletionStreamResponseChoicesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateChatCompletionStreamResponseChoicesInner - a model defined in OpenAPI

        delta: The delta of this CreateChatCompletionStreamResponseChoicesInner.
        finish_reason: The finish_reason of this CreateChatCompletionStreamResponseChoicesInner.
        index: The index of this CreateChatCompletionStreamResponseChoicesInner.
    """

    delta: ChatCompletionStreamResponseDelta = Field(alias="delta")
    finish_reason: Optional[str] = Field(alias="finish_reason")
    index: int = Field(alias="index")

CreateChatCompletionStreamResponseChoicesInner.update_forward_refs()
