# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.create_chat_completion_stream_response_choices_inner import CreateChatCompletionStreamResponseChoicesInner


class CreateChatCompletionStreamResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateChatCompletionStreamResponse - a model defined in OpenAPI

        id: The id of this CreateChatCompletionStreamResponse.
        choices: The choices of this CreateChatCompletionStreamResponse.
        created: The created of this CreateChatCompletionStreamResponse.
        model: The model of this CreateChatCompletionStreamResponse.
        system_fingerprint: The system_fingerprint of this CreateChatCompletionStreamResponse [Optional].
        object: The object of this CreateChatCompletionStreamResponse.
    """

    id: str = Field(alias="id")
    choices: List[CreateChatCompletionStreamResponseChoicesInner] = Field(alias="choices")
    created: int = Field(alias="created")
    model: Optional[str] = Field(alias="model")
    system_fingerprint: Optional[str] = Field(alias="system_fingerprint", default=None)
    object: str = Field(alias="object")

CreateChatCompletionStreamResponse.update_forward_refs()
