# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CreateMessageRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateMessageRequest - a model defined in OpenAPI

        role: The role of this CreateMessageRequest.
        content: The content of this CreateMessageRequest.
        file_ids: The file_ids of this CreateMessageRequest [Optional].
        metadata: The metadata of this CreateMessageRequest [Optional].
    """

    role: str = Field(alias="role")
    content: str = Field(alias="content")
    file_ids: Optional[List[str]] = Field(alias="file_ids", default=None)
    metadata: Optional[Dict[str, Any]] = Field(alias="metadata", default=None)

    @validator("content")
    def content_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("content")
    def content_max_length(cls, value):
        assert len(value) <= 32768
        return value

CreateMessageRequest.update_forward_refs()
