# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DeleteFileResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DeleteFileResponse - a model defined in OpenAPI

        id: The id of this DeleteFileResponse.
        object: The object of this DeleteFileResponse.
        deleted: The deleted of this DeleteFileResponse.
    """

    id: str = Field(alias="id")
    object: str = Field(alias="object")
    deleted: bool = Field(alias="deleted")

DeleteFileResponse.update_forward_refs()
