# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Error(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Error - a model defined in OpenAPI

        code: The code of this Error.
        message: The message of this Error.
        param: The param of this Error.
        type: The type of this Error.
    """

    code: str = Field(alias="code")
    message: str = Field(alias="message")
    param: str = Field(alias="param")
    type: str = Field(alias="type")

Error.update_forward_refs()
