# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class FineTuningJobEvent(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FineTuningJobEvent - a model defined in OpenAPI

        id: The id of this FineTuningJobEvent.
        created_at: The created_at of this FineTuningJobEvent.
        level: The level of this FineTuningJobEvent.
        message: The message of this FineTuningJobEvent.
        object: The object of this FineTuningJobEvent.
    """

    id: str = Field(alias="id")
    created_at: int = Field(alias="created_at")
    level: str = Field(alias="level")
    message: str = Field(alias="message")
    object: str = Field(alias="object")

FineTuningJobEvent.update_forward_refs()
