# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.fine_tuning_job_hyperparameters_n_epochs import FineTuningJobHyperparametersNEpochs


class FineTuningJobHyperparameters(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FineTuningJobHyperparameters - a model defined in OpenAPI

        n_epochs: The n_epochs of this FineTuningJobHyperparameters.
    """

    n_epochs: FineTuningJobHyperparametersNEpochs = Field(alias="n_epochs")

FineTuningJobHyperparameters.update_forward_refs()
