# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.image import Image


class ImagesResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ImagesResponse - a model defined in OpenAPI

        created: The created of this ImagesResponse.
        data: The data of this ImagesResponse.
    """

    created: int = Field(alias="created")
    data: List[Image] = Field(alias="data")

ImagesResponse.update_forward_refs()
