# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_step_object import RunStepObject


class ListRunStepsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListRunStepsResponse - a model defined in OpenAPI

        object: The object of this ListRunStepsResponse.
        data: The data of this ListRunStepsResponse.
        first_id: The first_id of this ListRunStepsResponse.
        last_id: The last_id of this ListRunStepsResponse.
        has_more: The has_more of this ListRunStepsResponse.
    """

    object: str = Field(alias="object")
    data: List[RunStepObject] = Field(alias="data")
    first_id: str = Field(alias="first_id")
    last_id: str = Field(alias="last_id")
    has_more: bool = Field(alias="has_more")

ListRunStepsResponse.update_forward_refs()
