# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.model import Model


class ListModelsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListModelsResponse - a model defined in OpenAPI

        object: The object of this ListModelsResponse.
        data: The data of this ListModelsResponse.
    """

    object: str = Field(alias="object")
    data: List[Model] = Field(alias="data")

ListModelsResponse.update_forward_refs()
