# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.message_stream_response_object import MessageStreamResponseObject


class ListMessagesStreamResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListMessagesStreamResponse - a model defined in OpenAPI

        object: The object of this ListMessagesStreamResponse.
        data: The data of this ListMessagesStreamResponse.
        first_id: The first_id of this ListMessagesStreamResponse.
        last_id: The last_id of this ListMessagesStreamResponse.
    """

    object: str = Field(alias="object")
    data: List[MessageStreamResponseObject] = Field(alias="data")
    first_id: str = Field(alias="first_id")
    last_id: str = Field(alias="last_id")

ListMessagesStreamResponse.update_forward_refs()
