# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_object import RunObject


class ListRunsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListRunsResponse - a model defined in OpenAPI

        object: The object of this ListRunsResponse.
        data: The data of this ListRunsResponse.
        first_id: The first_id of this ListRunsResponse.
        last_id: The last_id of this ListRunsResponse.
        has_more: The has_more of this ListRunsResponse.
    """

    object: str = Field(alias="object")
    data: List[RunObject] = Field(alias="data")
    first_id: str = Field(alias="first_id")
    last_id: str = Field(alias="last_id")
    has_more: bool = Field(alias="has_more")

ListRunsResponse.update_forward_refs()
