# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.message_content_image_file_object_image_file import MessageContentImageFileObjectImageFile


class MessageContentImageFileObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MessageContentImageFileObject - a model defined in OpenAPI

        type: The type of this MessageContentImageFileObject.
        image_file: The image_file of this MessageContentImageFileObject.
    """

    type: str = Field(alias="type")
    image_file: MessageContentImageFileObjectImageFile = Field(alias="image_file")

MessageContentImageFileObject.update_forward_refs()
