# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.message_content_text_annotations_file_path_object_file_path import MessageContentTextAnnotationsFilePathObjectFilePath


class MessageContentTextAnnotationsFilePathObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MessageContentTextAnnotationsFilePathObject - a model defined in OpenAPI

        type: The type of this MessageContentTextAnnotationsFilePathObject.
        text: The text of this MessageContentTextAnnotationsFilePathObject.
        file_path: The file_path of this MessageContentTextAnnotationsFilePathObject.
        start_index: The start_index of this MessageContentTextAnnotationsFilePathObject.
        end_index: The end_index of this MessageContentTextAnnotationsFilePathObject.
    """

    type: str = Field(alias="type")
    text: str = Field(alias="text")
    file_path: MessageContentTextAnnotationsFilePathObjectFilePath = Field(alias="file_path")
    start_index: int = Field(alias="start_index")
    end_index: int = Field(alias="end_index")

    @validator("start_index")
    def start_index_min(cls, value):
        assert value >= 0
        return value

    @validator("end_index")
    def end_index_min(cls, value):
        assert value >= 0
        return value

MessageContentTextAnnotationsFilePathObject.update_forward_refs()
