# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.message_content_image_file_object import MessageContentImageFileObject
from openapi_server.models.message_content_image_file_object_image_file import MessageContentImageFileObjectImageFile
# from openapi_server.models.message_content_text_object import MessageContentTextObject
from openapi_server.models.message_content_text_object_text import MessageContentTextObjectText


class MessageObjectContentInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MessageObjectContentInner - a model defined in OpenAPI

        type: The type of this MessageObjectContentInner.
        image_file: The image_file of this MessageObjectContentInner.
        text: The text of this MessageObjectContentInner.
    """

    type: str = Field(alias="type")
    image_file: Optional[MessageContentImageFileObjectImageFile] = Field(alias="image_file")
    text: Optional[MessageContentTextObjectText] = Field(alias="text", default=None)

MessageObjectContentInner.update_forward_refs()
