# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.message_content_delta_object_text import MessageContentDeltaObjectText


class MessageContentDeltaObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MessageContentDeltaObject - a model defined in OpenAPI

        type: The type of this MessageContentDeltaObject.
        text: The text of this MessageContentDeltaObject.
    """

    type: str = Field(alias="type")
    delta: MessageContentDeltaObjectText = Field(alias="delta")

MessageContentDeltaObject.update_forward_refs()
