# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Model(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Model - a model defined in OpenAPI

        id: The id of this Model.
        created: The created of this Model.
        object: The object of this Model.
        owned_by: The owned_by of this Model.
    """

    id: str = Field(alias="id")
    created: int = Field(alias="created")
    object: str = Field(alias="object")
    owned_by: str = Field(alias="owned_by")

Model.update_forward_refs()
