# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class OpenAIFile(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OpenAIFile - a model defined in OpenAPI

        id: The id of this OpenAIFile.
        bytes: The bytes of this OpenAIFile.
        created_at: The created_at of this OpenAIFile.
        filename: The filename of this OpenAIFile.
        object: The object of this OpenAIFile.
        purpose: The purpose of this OpenAIFile.
        status: The status of this OpenAIFile.
        status_details: The status_details of this OpenAIFile [Optional].
    """

    id: str = Field(alias="id")
    bytes: int = Field(alias="bytes")
    created_at: int = Field(alias="created_at")
    filename: str = Field(alias="filename")
    object: str = Field(alias="object")
    purpose: str = Field(alias="purpose")
    status: str = Field(alias="status")
    status_details: Optional[str] = Field(alias="status_details", default=None)

OpenAIFile.update_forward_refs()
