# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_step_details_message_creation_object_message_creation import RunStepDetailsMessageCreationObjectMessageCreation


class RunStepDetailsMessageCreationObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunStepDetailsMessageCreationObject - a model defined in OpenAPI

        type: The type of this RunStepDetailsMessageCreationObject.
        message_creation: The message_creation of this RunStepDetailsMessageCreationObject.
    """

    type: str = Field(alias="type")
    message_creation: RunStepDetailsMessageCreationObjectMessageCreation = Field(alias="message_creation")

RunStepDetailsMessageCreationObject.update_forward_refs()
