# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RunStepDetailsMessageCreationObjectMessageCreation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunStepDetailsMessageCreationObjectMessageCreation - a model defined in OpenAPI

        message_id: The message_id of this RunStepDetailsMessageCreationObjectMessageCreation.
    """

    message_id: str = Field(alias="message_id")

RunStepDetailsMessageCreationObjectMessageCreation.update_forward_refs()
