# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.assistant_object_tools_inner import AssistantObjectToolsInner
from openapi_server.models.run_completion_usage import RunCompletionUsage
from openapi_server.models.run_object_last_error import RunObjectLastError
from openapi_server.models.run_object_required_action import RunObjectRequiredAction


class RunObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunObject - a model defined in OpenAPI

        id: The id of this RunObject.
        object: The object of this RunObject.
        created_at: The created_at of this RunObject.
        thread_id: The thread_id of this RunObject.
        assistant_id: The assistant_id of this RunObject.
        status: The status of this RunObject.
        required_action: The required_action of this RunObject.
        last_error: The last_error of this RunObject.
        expires_at: The expires_at of this RunObject.
        started_at: The started_at of this RunObject.
        cancelled_at: The cancelled_at of this RunObject.
        failed_at: The failed_at of this RunObject.
        completed_at: The completed_at of this RunObject.
        model: The model of this RunObject.
        instructions: The instructions of this RunObject.
        tools: The tools of this RunObject.
        file_ids: The file_ids of this RunObject.
        metadata: The metadata of this RunObject.
        usage: The usage of this RunObject.
    """

    id: str = Field(alias="id")
    object: str = Field(alias="object")
    created_at: int = Field(alias="created_at")
    thread_id: str = Field(alias="thread_id")
    assistant_id: str = Field(alias="assistant_id")
    status: str = Field(alias="status")
    required_action: Optional[RunObjectRequiredAction] = Field(alias="required_action", default=None)
    last_error: RunObjectLastError = Field(alias="last_error", default=None)
    expires_at: int = Field(alias="expires_at", default=None)
    started_at: int = Field(alias="started_at", default=None)
    cancelled_at: int = Field(alias="cancelled_at", default=None)
    failed_at: int = Field(alias="failed_at")
    completed_at: int = Field(alias="completed_at")
    model: str = Field(alias="model")
    instructions: str = Field(alias="instructions")
    tools: List[AssistantObjectToolsInner] = Field(alias="tools")
    file_ids: List[str] = Field(alias="file_ids")
    metadata: Dict[str, Any] = Field(alias="metadata")
    usage: Optional[RunCompletionUsage] = Field(alias="usage")

RunObject.update_forward_refs()
