# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RunStepDetailsToolCallsRetrievalObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunStepDetailsToolCallsRetrievalObject - a model defined in OpenAPI

        id: The id of this RunStepDetailsToolCallsRetrievalObject.
        type: The type of this RunStepDetailsToolCallsRetrievalObject.
        retrieval: The retrieval of this RunStepDetailsToolCallsRetrievalObject.
    """

    id: str = Field(alias="id")
    type: str = Field(alias="type")
    retrieval: Dict[str, Any] = Field(alias="retrieval")

RunStepDetailsToolCallsRetrievalObject.update_forward_refs()
