# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_step_details_tool_calls_code_output_image_object_image import RunStepDetailsToolCallsCodeOutputImageObjectImage


class RunStepDetailsToolCallsCodeOutputImageObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunStepDetailsToolCallsCodeOutputImageObject - a model defined in OpenAPI

        type: The type of this RunStepDetailsToolCallsCodeOutputImageObject.
        image: The image of this RunStepDetailsToolCallsCodeOutputImageObject.
    """

    type: str = Field(alias="type")
    image: RunStepDetailsToolCallsCodeOutputImageObjectImage = Field(alias="image")

RunStepDetailsToolCallsCodeOutputImageObject.update_forward_refs()
