# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RunCompletionUsage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunCompletionUsage - a model defined in OpenAPI

        completion_tokens: The completion_tokens of this RunCompletionUsage.
        prompt_tokens: The prompt_tokens of this RunCompletionUsage.
        total_tokens: The total_tokens of this RunCompletionUsage.
    """

    completion_tokens: int = Field(alias="completion_tokens")
    prompt_tokens: int = Field(alias="prompt_tokens")
    total_tokens: int = Field(alias="total_tokens")

RunCompletionUsage.update_forward_refs()
