# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_step_details_message_creation_object import RunStepDetailsMessageCreationObject
from openapi_server.models.run_step_details_message_creation_object_message_creation import RunStepDetailsMessageCreationObjectMessageCreation
from openapi_server.models.run_step_details_tool_calls_object import RunStepDetailsToolCallsObject
from openapi_server.models.run_step_details_tool_calls_object_tool_calls_inner import RunStepDetailsToolCallsObjectToolCallsInner


class RunStepObjectStepDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunStepObjectStepDetails - a model defined in OpenAPI

        type: The type of this RunStepObjectStepDetails.
        message_creation: The message_creation of this RunStepObjectStepDetails.
        tool_calls: The tool_calls of this RunStepObjectStepDetails.
    """

    type: str = Field(alias="type")
    message_creation: RunStepDetailsMessageCreationObjectMessageCreation = Field(alias="message_creation")
    tool_calls: List[RunStepDetailsToolCallsObjectToolCallsInner] = Field(alias="tool_calls")

RunStepObjectStepDetails.update_forward_refs()
