# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_object_required_action_submit_tool_outputs import RunObjectRequiredActionSubmitToolOutputs


class RunObjectRequiredAction(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunObjectRequiredAction - a model defined in OpenAPI

        type: The type of this RunObjectRequiredAction.
        submit_tool_outputs: The submit_tool_outputs of this RunObjectRequiredAction.
    """

    type: str = Field(alias="type")
    submit_tool_outputs: RunObjectRequiredActionSubmitToolOutputs = Field(alias="submit_tool_outputs")

RunObjectRequiredAction.update_forward_refs()
