# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_tool_call_object_function import RunToolCallObjectFunction


class RunToolCallObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunToolCallObject - a model defined in OpenAPI

        id: The id of this RunToolCallObject.
        type: The type of this RunToolCallObject.
        function: The function of this RunToolCallObject.
    """

    id: str = Field(alias="id")
    type: str = Field(alias="type")
    function: RunToolCallObjectFunction = Field(alias="function")

RunToolCallObject.update_forward_refs()
