# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SubmitToolOutputsRunRequestToolOutputsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SubmitToolOutputsRunRequestToolOutputsInner - a model defined in OpenAPI

        tool_call_id: The tool_call_id of this SubmitToolOutputsRunRequestToolOutputsInner [Optional].
        output: The output of this SubmitToolOutputsRunRequestToolOutputsInner [Optional].
    """

    tool_call_id: Optional[str] = Field(alias="tool_call_id", default=None)
    output: Optional[str] = Field(alias="output", default=None)

SubmitToolOutputsRunRequestToolOutputsInner.update_forward_refs()
