# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.submit_tool_outputs_run_request_tool_outputs_inner import SubmitToolOutputsRunRequestToolOutputsInner


class SubmitToolOutputsRunRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SubmitToolOutputsRunRequest - a model defined in OpenAPI

        tool_outputs: The tool_outputs of this SubmitToolOutputsRunRequest.
    """

    tool_outputs: List[SubmitToolOutputsRunRequestToolOutputsInner] = Field(alias="tool_outputs")

SubmitToolOutputsRunRequest.update_forward_refs()
