# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ThreadObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ThreadObject - a model defined in OpenAPI

        id: The id of this ThreadObject.
        object: The object of this ThreadObject.
        created_at: The created_at of this ThreadObject.
        metadata: The metadata of this ThreadObject.
    """

    id: str = Field(alias="id")
    object: str = Field(alias="object")
    created_at: int = Field(alias="created_at")
    metadata: Dict[str, Any] = Field(alias="metadata")

ThreadObject.update_forward_refs()
